APP_NAME = "TIPS Prompt Manager"
APP_VERSION = "1.0.0"
AUTHOR = "HaoXiang Huang"
EMAIL = "didadida1688@gmail.com"
HOMEPAGE = "https://nextweb4.github.io/"
GITHUB = "https://github.com/NextWeb4"
COPYRIGHT = "Copyright (c) 2026 HaoXiang Huang"
